export const mainElements = [
  {
    index: 1,
    symbol: "H",
    name: "Hydrogen",
    atomicNumber: 1,
    position: { row: 1, col: 1 },
    category: "Nonmetal",
    atomicRadius: "53 pm",
    atomicWeight: "1.008 amu",
    density: "0.00008988 g/cm³",
    electroNegativity: "2.20",
    meltingPoint: "14.01 K",
    boilingPoint: "20.28 K",
    standardState: "Gas",
    ionizationEnergy: "1312 kJ/mol",
    discoveredBy: "Henry Cavendish",
    discoveredYear: "1766",
    howToPronounce: "HY-dro-jen",
    bg: "#173d40",
    cardBG: "#102c2e",
    secondCardBG: "#173d40",
    textColor: "#4fdbe5",
  },
  {
    index: 2,
    symbol: "He",
    name: "Helium",
    atomicNumber: 2,
    position: { row: 1, col: 18 },
    category: "Noble Gas",
    atomicRadius: "31 pm",
    atomicWeight: "4.0026 amu",
    density: "0.0001785 g/cm³",
    electroNegativity: "0",
    meltingPoint: "0 K",
    boilingPoint: "4.22 K",
    standardState: "Gas",
    ionizationEnergy: "2372 kJ/mol",
    discoveredBy: "Pierre Janssen & Norman Lockyer",
    discoveredYear: "1868",
    howToPronounce: "HEE-lee-um",
    bg: "#0e2b57",
    cardBG: "#0a1e3d",
    secondCardBG: "#0e2b57",
    textColor: "#87b7ff",
  },
  {
    index: 3,
    symbol: "Li",
    name: "Lithium",
    atomicNumber: 3,
    position: { row: 2, col: 1 },
    category: "Alkali Metal",
    atomicRadius: "167 pm",
    atomicWeight: "6.94 amu",
    density: "0.534 g/cm³",
    electroNegativity: "0.98",
    meltingPoint: "453.69 K",
    boilingPoint: "1603 K",
    standardState: "Solid",
    ionizationEnergy: "520 kJ/mol",
    discoveredBy: "Johan August Arfvedson",
    discoveredYear: "1817",
    howToPronounce: "LITH-ee-um",
    bg: "#3e204d",
    cardBG: "#2d1738",
    secondCardBG: "#3e204d",
    textColor: "#d582ff",
  },
  {
    index: 4,
    symbol: "Be",
    name: "Beryllium",
    atomicNumber: 4,
    position: { row: 2, col: 2 },
    category: "Alkaline Earth Metal",
    atomicRadius: "112 pm",
    atomicWeight: "9.0122 amu",
    density: "1.85 g/cm³",
    electroNegativity: "1.57",
    meltingPoint: "1560 K",
    boilingPoint: "2742 K",
    standardState: "Solid",
    ionizationEnergy: "900 kJ/mol",
    discoveredBy: "Louis Nicolas Vauquelin",
    discoveredYear: "1798",
    howToPronounce: "beh-RILL-ee-um",
    bg: "#45434c",
    cardBG: "#45434c",
    secondCardBG: "#2e2d33",
    textColor: "#f6f4ff",
  },
  {
    index: 5,
    symbol: "B",
    name: "Boron",
    atomicNumber: 5,
    position: { row: 2, col: 13 },
    category: "Metalloid",
    atomicRadius: "87 pm",
    atomicWeight: "10.81 amu",
    density: "2.34 g/cm³",
    electroNegativity: "2.04",
    meltingPoint: "2349 K",
    boilingPoint: "4200 K",
    standardState: "Solid",
    ionizationEnergy: "800 kJ/mol",
    discoveredBy: "Joseph Louis Gay-Lussac & Humphry Davy",
    discoveredYear: "1808",
    howToPronounce: "BOHR-on",
    bg: "#23274d",
    cardBG: "#171a33",
    secondCardBG: "#23274d",
    textColor: "#a3abff",
  },
  {
    index: 6,
    symbol: "C",
    name: "Carbon",
    atomicNumber: 6,
    position: { row: 2, col: 14 },
    category: "Nonmetal",
    atomicRadius: "67 pm",
    atomicWeight: "12.011 amu",
    density: "2.267 g/cm³",
    electroNegativity: "2.55",
    meltingPoint: "3823 K",
    boilingPoint: "4300 K",
    standardState: "Solid",
    ionizationEnergy: "1086 kJ/mol",
    discoveredBy: "Ancient",
    discoveredYear: "unknown",
    howToPronounce: "CAR-bon",
    bg: "#173d40",
    cardBG: "#102c2e",
    secondCardBG: "#173d40",
    textColor: "#4fdbe5",
  },
  {
    index: 7,
    symbol: "N",
    name: "Nitrogen",
    atomicNumber: 7,
    position: { row: 2, col: 15 },
    category: "Nonmetal",
    atomicRadius: "56 pm",
    atomicWeight: "14.007 amu",
    density: "0.0012506 g/cm³",
    electroNegativity: "3.04",
    meltingPoint: "63.15 K",
    boilingPoint: "77.36 K",
    standardState: "Gas",
    ionizationEnergy: "1402 kJ/mol",
    discoveredBy: "Daniel Rutherford",
    discoveredYear: "1772",
    howToPronounce: "NY-tro-jen",
    bg: "#173d40",
    cardBG: "#102c2e",
    secondCardBG: "#173d40",
    textColor: "#4fdbe5",
  },
  {
    index: 8,
    symbol: "O",
    name: "Oxygen",
    atomicNumber: 8,
    position: { row: 2, col: 16 },
    category: "Nonmetal",
    atomicRadius: "48 pm",
    atomicWeight: "15.999 amu",
    density: "0.001429 g/cm³",
    electroNegativity: "3.44",
    meltingPoint: "54.36 K",
    boilingPoint: "90.20 K",
    standardState: "Gas",
    ionizationEnergy: "1314 kJ/mol",
    discoveredBy: "Carl Wilhelm Scheele & Joseph Priestley",
    discoveredYear: "1774",
    howToPronounce: "OX-i-jen",
    bg: "#173d40",
    cardBG: "#102c2e",
    secondCardBG: "#173d40",
    textColor: "#4fdbe5",
  },
  {
    index: 9,
    symbol: "F",
    name: "Fluorine",
    atomicNumber: 9,
    position: { row: 2, col: 17 },
    category: "Halogen",
    atomicRadius: "42 pm",
    atomicWeight: "18.998 amu",
    density: "0.001696 g/cm³",
    electroNegativity: "3.98",
    meltingPoint: "53.48 K",
    boilingPoint: "85.03 K",
    standardState: "Gas",
    ionizationEnergy: "1681 kJ/mol",
    discoveredBy: "Henri Moissan",
    discoveredYear: "1886",
    howToPronounce: "FLOOR-een",
    bg: "#4d0044",
    cardBG: "#33002d",
    secondCardBG: "#4d0044",
    textColor: "#ff99f3",
  },
  {
    index: 10,
    symbol: "Ne",
    name: "Neon",
    atomicNumber: 10,
    position: { row: 2, col: 18 },
    category: "Noble Gas",
    atomicRadius: "38 pm",
    atomicWeight: "20.180 amu",
    density: "0.0008999 g/cm³",
    electroNegativity: "0",
    meltingPoint: "24.56 K",
    boilingPoint: "27.07 K",
    standardState: "Gas",
    ionizationEnergy: "2080 kJ/mol",
    discoveredBy: "William Ramsay & Morris Travers",
    discoveredYear: "1898",
    howToPronounce: "NEE-on",
    bg: "#0e2b57",
    cardBG: "#0a1e3d",
    secondCardBG: "#0e2b57",
    textColor: "#87b7ff",
  },
  {
    index: 11,
    symbol: "Na",
    name: "Sodium",
    atomicNumber: 11,
    position: { row: 3, col: 1 },
    category: "Alkali Metal",
    atomicRadius: "190 pm",
    atomicWeight: "22.990 amu",
    density: "0.971 g/cm³",
    electroNegativity: "0.93",
    meltingPoint: "370.87 K",
    boilingPoint: "1156 K",
    standardState: "Solid",
    ionizationEnergy: "496 kJ/mol",
    discoveredBy: "Humphry Davy",
    discoveredYear: "1807",
    howToPronounce: "SO-dee-um",
    bg: "#3e204d",
    cardBG: "#2d1738",
    secondCardBG: "#3e204d",
    textColor: "#d582ff",
  },
  {
    index: 12,
    symbol: "Mg",
    name: "Magnesium",
    atomicNumber: 12,
    position: { row: 3, col: 2 },
    category: "Alkaline Earth Metal",
    atomicRadius: "145 pm",
    atomicWeight: "24.305 amu",
    density: "1.738 g/cm³",
    electroNegativity: "1.31",
    meltingPoint: "923 K",
    boilingPoint: "1363 K",
    standardState: "Solid",
    ionizationEnergy: "738 kJ/mol",
    discoveredBy: "Joseph Black",
    discoveredYear: "1755",
    howToPronounce: "mag-NEE-zee-um",
    bg: "#45434c",
    cardBG: "#45434c",
    secondCardBG: "#2e2d33",
    textColor: "#f6f4ff",
  },
  {
    index: 13,
    symbol: "Al",
    name: "Aluminium",
    atomicNumber: 13,
    position: { row: 3, col: 13 },
    category: "Post-transition Metal",
    atomicRadius: "118 pm",
    atomicWeight: "26.982 amu",
    density: "2.70 g/cm³",
    electroNegativity: "1.61",
    meltingPoint: "933.47 K",
    boilingPoint: "2792 K",
    standardState: "Solid",
    ionizationEnergy: "578 kJ/mol",
    discoveredBy: "Hans Christian Ørsted",
    discoveredYear: "1825",
    howToPronounce: "al-LOO-min-um",
    bg: "#331f1f",
    cardBG: "#241616",
    secondCardBG: "#331f1f",
    textColor: "#ff9a9a",
  },
  {
    index: 14,
    symbol: "Si",
    name: "Silicon",
    atomicNumber: 14,
    position: { row: 3, col: 14 },
    category: "Metalloid",
    atomicRadius: "111 pm",
    atomicWeight: "28.085 amu",
    density: "2.3296 g/cm³",
    electroNegativity: "1.90",
    meltingPoint: "1687 K",
    boilingPoint: "3538 K",
    standardState: "Solid",
    ionizationEnergy: "786 kJ/mol",
    discoveredBy: "Jöns Jacob Berzelius",
    discoveredYear: "1824",
    howToPronounce: "SILL-i-kon",
    bg: "#23274d",
    cardBG: "#171a33",
    secondCardBG: "#23274d",
    textColor: "#a3abff",
  },
  {
    index: 15,
    symbol: "P",
    name: "Phosphorus",
    atomicNumber: 15,
    position: { row: 3, col: 15 },
    category: "Nonmetal",
    atomicRadius: "98 pm",
    atomicWeight: "30.974 amu",
    density: "1.82 g/cm³",
    electroNegativity: "2.19",
    meltingPoint: "317.30 K",
    boilingPoint: "553.65 K",
    standardState: "Solid",
    ionizationEnergy: "1012 kJ/mol",
    discoveredBy: "Hennig Brand",
    discoveredYear: "1669",
    howToPronounce: "FOS-fo-rus",
    bg: "#173d40",
    cardBG: "#102c2e",
    secondCardBG: "#173d40",
    textColor: "#4fdbe5",
  },
  {
    index: 16,
    symbol: "S",
    name: "Sulfur",
    atomicNumber: 16,
    position: { row: 3, col: 16 },
    category: "Nonmetal",
    atomicRadius: "88 pm",
    atomicWeight: "32.06 amu",
    density: "2.07 g/cm³",
    electroNegativity: "2.58",
    meltingPoint: "388.36 K",
    boilingPoint: "717.87 K",
    standardState: "Solid",
    ionizationEnergy: "1000 kJ/mol",
    discoveredBy: "Ancient",
    discoveredYear: "unknown",
    howToPronounce: "SUL-fur",
    bg: "#173d40",
    cardBG: "#102c2e",
    secondCardBG: "#173d40",
    textColor: "#4fdbe5",
  },
  {
    index: 17,
    symbol: "Cl",
    name: "Chlorine",
    atomicNumber: 17,
    position: { row: 3, col: 17 },
    category: "Halogen",
    atomicRadius: "79 pm",
    atomicWeight: "35.45 amu",
    density: "0.003214 g/cm³",
    electroNegativity: "3.16",
    meltingPoint: "171.6 K",
    boilingPoint: "239.11 K",
    standardState: "Gas",
    ionizationEnergy: "1251 kJ/mol",
    discoveredBy: "Carl Wilhelm Scheele",
    discoveredYear: "1774",
    howToPronounce: "KLOR-een",
    bg: "#4d0044",
    cardBG: "#33002d",
    secondCardBG: "#4d0044",
    textColor: "#ff99f3",
  },
  {
    index: 18,
    symbol: "Ar",
    name: "Argon",
    atomicNumber: 18,
    position: { row: 3, col: 18 },
    category: "Noble Gas",
    atomicRadius: "71 pm",
    atomicWeight: "39.948 amu",
    density: "0.001784 g/cm³",
    electroNegativity: "0",
    meltingPoint: "83.81 K",
    boilingPoint: "87.30 K",
    standardState: "Gas",
    ionizationEnergy: "1521 kJ/mol",
    discoveredBy: "Lord Rayleigh & William Ramsay",
    discoveredYear: "1894",
    howToPronounce: "AR-gon",
    bg: "#0e2b57",
    cardBG: "#0a1e3d",
    secondCardBG: "#0e2b57",
    textColor: "#87b7ff",
  },
  {
    index: 19,
    symbol: "K",
    name: "Potassium",
    atomicNumber: 19,
    position: { row: 4, col: 1 },
    category: "Alkali Metal",
    atomicRadius: "243 pm",
    atomicWeight: "39.098 amu",
    density: "0.862 g/cm³",
    electroNegativity: "0.82",
    meltingPoint: "336.53 K",
    boilingPoint: "1032 K",
    standardState: "Solid",
    ionizationEnergy: "419 kJ/mol",
    discoveredBy: "Humphry Davy",
    discoveredYear: "1807",
    howToPronounce: "po-TASS-ee-um",
    bg: "#3e204d",
    cardBG: "#2d1738",
    secondCardBG: "#3e204d",
    textColor: "#d582ff",
  },
  {
    index: 20,
    symbol: "Ca",
    name: "Calcium",
    atomicNumber: 20,
    position: { row: 4, col: 2 },
    category: "Alkaline Earth Metal",
    atomicRadius: "194 pm",
    atomicWeight: "40.078 amu",
    density: "1.54 g/cm³",
    electroNegativity: "1.00",
    meltingPoint: "1115 K",
    boilingPoint: "1757 K",
    standardState: "Solid",
    ionizationEnergy: "590 kJ/mol",
    discoveredBy: "Humphry Davy",
    discoveredYear: "1808",
    howToPronounce: "KAL-see-um",
    bg: "#45434c",
    cardBG: "#45434c",
    secondCardBG: "#2e2d33",
    textColor: "#f6f4ff",
  },
  {
    index: 21,
    symbol: "Sc",
    name: "Scandium",
    atomicNumber: 21,
    position: { row: 4, col: 3 },
    category: "Transition Metal",
    atomicRadius: "184 pm",
    atomicWeight: "44.956 amu",
    density: "2.985 g/cm³",
    electroNegativity: "1.36",
    meltingPoint: "1814 K",
    boilingPoint: "3109 K",
    standardState: "Solid",
    ionizationEnergy: "633 kJ/mol",
    discoveredBy: "Lars Fredrik Nilson",
    discoveredYear: "1879",
    howToPronounce: "SCAN-dee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 22,
    symbol: "Ti",
    name: "Titanium",
    atomicNumber: 22,
    position: { row: 4, col: 4 },
    category: "Transition Metal",
    atomicRadius: "176 pm",
    atomicWeight: "47.867 amu",
    density: "4.506 g/cm³",
    electroNegativity: "1.54",
    meltingPoint: "1941 K",
    boilingPoint: "3560 K",
    standardState: "Solid",
    ionizationEnergy: "658 kJ/mol",
    discoveredBy: "William Gregor",
    discoveredYear: "1791",
    howToPronounce: "tie-TAY-nee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 23,
    symbol: "V",
    name: "Vanadium",
    atomicNumber: 23,
    position: { row: 4, col: 5 },
    category: "Transition Metal",
    atomicRadius: "171 pm",
    atomicWeight: "50.942 amu",
    density: "6.11 g/cm³",
    electroNegativity: "1.63",
    meltingPoint: "2183 K",
    boilingPoint: "3680 K",
    standardState: "Solid",
    ionizationEnergy: "651 kJ/mol",
    discoveredBy: "Andrés Manuel del Río",
    discoveredYear: "1801",
    howToPronounce: "va-NAY-dee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 24,
    symbol: "Cr",
    name: "Chromium",
    atomicNumber: 24,
    position: { row: 4, col: 6 },
    category: "Transition Metal",
    atomicRadius: "166 pm",
    atomicWeight: "51.996 amu",
    density: "7.15 g/cm³",
    electroNegativity: "1.66",
    meltingPoint: "2180 K",
    boilingPoint: "2944 K",
    standardState: "Solid",
    ionizationEnergy: "653 kJ/mol",
    discoveredBy: "Louis Nicolas Vauquelin",
    discoveredYear: "1797",
    howToPronounce: "KROH-mee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 25,
    symbol: "Mn",
    name: "Manganese",
    atomicNumber: 25,
    position: { row: 4, col: 7 },
    category: "Transition Metal",
    atomicRadius: "161 pm",
    atomicWeight: "54.938 amu",
    density: "7.44 g/cm³",
    electroNegativity: "1.55",
    meltingPoint: "1519 K",
    boilingPoint: "2334 K",
    standardState: "Solid",
    ionizationEnergy: "717 kJ/mol",
    discoveredBy: "Johan Gottlieb Gahn",
    discoveredYear: "1774",
    howToPronounce: "MANG-ga-nees",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 26,
    symbol: "Fe",
    name: "Iron",
    atomicNumber: 26,
    position: { row: 4, col: 8 },
    category: "Transition Metal",
    atomicRadius: "156 pm",
    atomicWeight: "55.845 amu",
    density: "7.874 g/cm³",
    electroNegativity: "1.83",
    meltingPoint: "1811 K",
    boilingPoint: "3134 K",
    standardState: "Solid",
    ionizationEnergy: "762 kJ/mol",
    discoveredBy: "Ancient",
    discoveredYear: "unknown",
    howToPronounce: "EYE-urn",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 27,
    symbol: "Co",
    name: "Cobalt",
    atomicNumber: 27,
    position: { row: 4, col: 9 },
    category: "Transition Metal",
    atomicRadius: "152 pm",
    atomicWeight: "58.933 amu",
    density: "8.86 g/cm³",
    electroNegativity: "1.88",
    meltingPoint: "1768 K",
    boilingPoint: "3200 K",
    standardState: "Solid",
    ionizationEnergy: "760 kJ/mol",
    discoveredBy: "Georg Brandt",
    discoveredYear: "1735",
    howToPronounce: "KO-balt",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 28,
    symbol: "Ni",
    name: "Nickel",
    atomicNumber: 28,
    position: { row: 4, col: 10 },
    category: "Transition Metal",
    atomicRadius: "149 pm",
    atomicWeight: "58.693 amu",
    density: "8.912 g/cm³",
    electroNegativity: "1.91",
    meltingPoint: "1728 K",
    boilingPoint: "3186 K",
    standardState: "Solid",
    ionizationEnergy: "737 kJ/mol",
    discoveredBy: "Axel Fredrik Cronstedt",
    discoveredYear: "1751",
    howToPronounce: "NIK-uhl",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 29,
    symbol: "Cu",
    name: "Copper",
    atomicNumber: 29,
    position: { row: 4, col: 11 },
    category: "Transition Metal",
    atomicRadius: "145 pm",
    atomicWeight: "63.546 amu",
    density: "8.96 g/cm³",
    electroNegativity: "1.90",
    meltingPoint: "1357.77 K",
    boilingPoint: "2835 K",
    standardState: "Solid",
    ionizationEnergy: "745 kJ/mol",
    discoveredBy: "Ancient",
    discoveredYear: "unknown",
    howToPronounce: "KOP-per",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 30,
    symbol: "Zn",
    name: "Zinc",
    atomicNumber: 30,
    position: { row: 4, col: 12 },
    category: "Transition Metal",
    atomicRadius: "142 pm",
    atomicWeight: "65.38 amu",
    density: "7.14 g/cm³",
    electroNegativity: "1.65",
    meltingPoint: "692.68 K",
    boilingPoint: "1180 K",
    standardState: "Solid",
    ionizationEnergy: "906 kJ/mol",
    discoveredBy: "India (Ancient)",
    discoveredYear: "1000s",
    howToPronounce: "ZINK",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 31,
    symbol: "Ga",
    name: "Gallium",
    atomicNumber: 31,
    position: { row: 4, col: 13 },
    category: "Post-transition Metal",
    atomicRadius: "136 pm",
    atomicWeight: "69.723 amu",
    density: "5.91 g/cm³",
    electroNegativity: "1.81",
    meltingPoint: "302.91 K",
    boilingPoint: "2477 K",
    standardState: "Solid",
    ionizationEnergy: "579 kJ/mol",
    discoveredBy: "Paul Émile Lecoq de Boisbaudran",
    discoveredYear: "1875",
    howToPronounce: "GAL-ee-um",
    bg: "#331f1f",
    cardBG: "#241616",
    secondCardBG: "#331f1f",
    textColor: "#ff9a9a",
  },
  {
    index: 32,
    symbol: "Ge",
    name: "Germanium",
    atomicNumber: 32,
    position: { row: 4, col: 14 },
    category: "Metalloid",
    atomicRadius: "125 pm",
    atomicWeight: "72.630 amu",
    density: "5.323 g/cm³",
    electroNegativity: "2.01",
    meltingPoint: "1211 K",
    boilingPoint: "3106 K",
    standardState: "Solid",
    ionizationEnergy: "762 kJ/mol",
    discoveredBy: "Clemens Winkler",
    discoveredYear: "1886",
    howToPronounce: "jer-MAY-nee-um",
    bg: "#23274d",
    cardBG: "#171a33",
    secondCardBG: "#23274d",
    textColor: "#a3abff",
  },
  {
    index: 33,
    symbol: "As",
    name: "Arsenic",
    atomicNumber: 33,
    position: { row: 4, col: 15 },
    category: "Metalloid",
    atomicRadius: "114 pm",
    atomicWeight: "74.922 amu",
    density: "5.727 g/cm³",
    electroNegativity: "2.18",
    meltingPoint: "1090 K (sublimes)",
    boilingPoint: "887 K (sublimation)",
    standardState: "Solid",
    ionizationEnergy: "947 kJ/mol",
    discoveredBy: "Albertus Magnus",
    discoveredYear: "1250",
    howToPronounce: "AR-se-nik",
    bg: "#23274d",
    cardBG: "#171a33",
    secondCardBG: "#23274d",
    textColor: "#a3abff",
  },
  {
    index: 34,
    symbol: "Se",
    name: "Selenium",
    atomicNumber: 34,
    position: { row: 4, col: 16 },
    category: "Nonmetal",
    atomicRadius: "103 pm",
    atomicWeight: "78.971 amu",
    density: "4.81 g/cm³",
    electroNegativity: "2.55",
    meltingPoint: "494 K",
    boilingPoint: "958 K",
    standardState: "Solid",
    ionizationEnergy: "941 kJ/mol",
    discoveredBy: "Jöns Jacob Berzelius",
    discoveredYear: "1817",
    howToPronounce: "si-LEE-nee-um",
    bg: "#173d40",
    cardBG: "#102c2e",
    secondCardBG: "#173d40",
    textColor: "#4fdbe5",
  },
  {
    index: 35,
    symbol: "Br",
    name: "Bromine",
    atomicNumber: 35,
    position: { row: 4, col: 17 },
    category: "Halogen",
    atomicRadius: "94 pm",
    atomicWeight: "79.904 amu",
    density: "3.12 g/cm³",
    electroNegativity: "2.96",
    meltingPoint: "265.8 K",
    boilingPoint: "332.0 K",
    standardState: "Liquid",
    ionizationEnergy: "1140 kJ/mol",
    discoveredBy: "Antoine Jérôme Balard",
    discoveredYear: "1826",
    howToPronounce: "BROH-meen",
    bg: "#4d0044",
    cardBG: "#33002d",
    secondCardBG: "#4d0044",
    textColor: "#ff99f3",
  },
  {
    index: 36,
    symbol: "Kr",
    name: "Krypton",
    atomicNumber: 36,
    position: { row: 4, col: 18 },
    category: "Noble Gas",
    atomicRadius: "88 pm",
    atomicWeight: "83.798 amu",
    density: "0.003733 g/cm³",
    electroNegativity: "3.00",
    meltingPoint: "115.78 K",
    boilingPoint: "119.93 K",
    standardState: "Gas",
    ionizationEnergy: "1351 kJ/mol",
    discoveredBy: "William Ramsay & Morris Travers",
    discoveredYear: "1898",
    howToPronounce: "KRIP-ton",
    bg: "#0e2b57",
    cardBG: "#0a1e3d",
    secondCardBG: "#0e2b57",
    textColor: "#87b7ff",
  },
  {
    index: 37,
    symbol: "Rb",
    name: "Rubidium",
    atomicNumber: 37,
    position: { row: 5, col: 1 },
    category: "Alkali Metal",
    atomicRadius: "303 pm",
    atomicWeight: "85.468 amu",
    density: "1.532 g/cm³",
    electroNegativity: "0.82",
    meltingPoint: "312.46 K",
    boilingPoint: "961 K",
    standardState: "Solid",
    ionizationEnergy: "403 kJ/mol",
    discoveredBy: "Robert Bunsen & Gustav Kirchhoff",
    discoveredYear: "1861",
    howToPronounce: "roo-BID-ee-um",
    bg: "#3e204d",
    cardBG: "#2d1738",
    secondCardBG: "#3e204d",
    textColor: "#d582ff",
  },
  {
    index: 38,
    symbol: "Sr",
    name: "Strontium",
    atomicNumber: 38,
    position: { row: 5, col: 2 },
    category: "Alkaline Earth Metal",
    atomicRadius: "249 pm",
    atomicWeight: "87.62 amu",
    density: "2.64 g/cm³",
    electroNegativity: "0.95",
    meltingPoint: "1050 K",
    boilingPoint: "1655 K",
    standardState: "Solid",
    ionizationEnergy: "550 kJ/mol",
    discoveredBy: "Adair Crawford",
    discoveredYear: "1790",
    howToPronounce: "STRON-shee-um",
    bg: "#45434c",
    cardBG: "#45434c",
    secondCardBG: "#2e2d33",
    textColor: "#f6f4ff",
  },
  {
    index: 39,
    symbol: "Y",
    name: "Yttrium",
    atomicNumber: 39,
    position: { row: 5, col: 3 },
    category: "Transition Metal",
    atomicRadius: "219 pm",
    atomicWeight: "88.906 amu",
    density: "4.47 g/cm³",
    electroNegativity: "1.22",
    meltingPoint: "1799 K",
    boilingPoint: "3609 K",
    standardState: "Solid",
    ionizationEnergy: "600 kJ/mol",
    discoveredBy: "Johan Gadolin",
    discoveredYear: "1794",
    howToPronounce: "IT-ree-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 40,
    symbol: "Zr",
    name: "Zirconium",
    atomicNumber: 40,
    position: { row: 5, col: 4 },
    category: "Transition Metal",
    atomicRadius: "186 pm",
    atomicWeight: "91.224 amu",
    density: "6.52 g/cm³",
    electroNegativity: "1.33",
    meltingPoint: "2128 K",
    boilingPoint: "4682 K",
    standardState: "Solid",
    ionizationEnergy: "640 kJ/mol",
    discoveredBy: "Martin Heinrich Klaproth",
    discoveredYear: "1789",
    howToPronounce: "zer-KOH-nee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 41,
    symbol: "Nb",
    name: "Niobium",
    atomicNumber: 41,
    position: { row: 5, col: 5 },
    category: "Transition Metal",
    atomicRadius: "146 pm",
    atomicWeight: "92.906 amu",
    density: "8.57 g/cm³",
    electroNegativity: "1.6",
    meltingPoint: "2750 K",
    boilingPoint: "5017 K",
    standardState: "Solid",
    ionizationEnergy: "652 kJ/mol",
    discoveredBy: "Charles Hatchett",
    discoveredYear: "1801",
    howToPronounce: "NIE-oh-bee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 42,
    symbol: "Mo",
    name: "Molybdenum",
    atomicNumber: 42,
    position: { row: 5, col: 6 },
    category: "Transition Metal",
    atomicRadius: "139 pm",
    atomicWeight: "95.95 amu",
    density: "10.28 g/cm³",
    electroNegativity: "2.16",
    meltingPoint: "2896 K",
    boilingPoint: "4912 K",
    standardState: "Solid",
    ionizationEnergy: "684 kJ/mol",
    discoveredBy: "Carl Wilhelm Scheele",
    discoveredYear: "1778",
    howToPronounce: "mol-IB-den-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 43,
    symbol: "Tc",
    name: "Technetium",
    atomicNumber: 43,
    position: { row: 5, col: 7 },
    category: "Transition Metal",
    atomicRadius: "136 pm",
    atomicWeight: "98 amu",
    density: "11 g/cm³",
    electroNegativity: "1.9",
    meltingPoint: "2430 K",
    boilingPoint: "4538 K",
    standardState: "Solid",
    ionizationEnergy: "702 kJ/mol",
    discoveredBy: "Carlo Perrier & Emilio Segrè",
    discoveredYear: "1937",
    howToPronounce: "tek-NEE-shee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 44,
    symbol: "Ru",
    name: "Ruthenium",
    atomicNumber: 44,
    position: { row: 5, col: 8 },
    category: "Transition Metal",
    atomicRadius: "134 pm",
    atomicWeight: "101.07 amu",
    density: "12.37 g/cm³",
    electroNegativity: "2.2",
    meltingPoint: "2607 K",
    boilingPoint: "4423 K",
    standardState: "Solid",
    ionizationEnergy: "710 kJ/mol",
    discoveredBy: "Karl Ernst Claus",
    discoveredYear: "1844",
    howToPronounce: "roo-THEE-nee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 45,
    symbol: "Rh",
    name: "Rhodium",
    atomicNumber: 45,
    position: { row: 5, col: 9 },
    category: "Transition Metal",
    atomicRadius: "134 pm",
    atomicWeight: "102.91 amu",
    density: "12.41 g/cm³",
    electroNegativity: "2.28",
    meltingPoint: "2237 K",
    boilingPoint: "3968 K",
    standardState: "Solid",
    ionizationEnergy: "720 kJ/mol",
    discoveredBy: "William Hyde Wollaston",
    discoveredYear: "1803",
    howToPronounce: "ROH-dee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 46,
    symbol: "Pd",
    name: "Palladium",
    atomicNumber: 46,
    position: { row: 5, col: 10 },
    category: "Transition Metal",
    atomicRadius: "137 pm",
    atomicWeight: "106.42 amu",
    density: "12.02 g/cm³",
    electroNegativity: "2.20",
    meltingPoint: "1828.05 K",
    boilingPoint: "3236 K",
    standardState: "Solid",
    ionizationEnergy: "804 kJ/mol",
    discoveredBy: "William Hyde Wollaston",
    discoveredYear: "1803",
    howToPronounce: "pal-LAY-dee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 47,
    symbol: "Ag",
    name: "Silver",
    atomicNumber: 47,
    position: { row: 5, col: 11 },
    category: "Transition Metal",
    atomicRadius: "144 pm",
    atomicWeight: "107.87 amu",
    density: "10.49 g/cm³",
    electroNegativity: "1.93",
    meltingPoint: "1234.93 K",
    boilingPoint: "2435 K",
    standardState: "Solid",
    ionizationEnergy: "731 kJ/mol",
    discoveredBy: "Ancient",
    discoveredYear: "unknown",
    howToPronounce: "SIL-ver",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 48,
    symbol: "Cd",
    name: "Cadmium",
    atomicNumber: 48,
    position: { row: 5, col: 12 },
    category: "Transition Metal",
    atomicRadius: "151 pm",
    atomicWeight: "112.41 amu",
    density: "8.65 g/cm³",
    electroNegativity: "1.69",
    meltingPoint: "594.22 K",
    boilingPoint: "1040 K",
    standardState: "Solid",
    ionizationEnergy: "868 kJ/mol",
    discoveredBy: "Friedrich Stromeyer",
    discoveredYear: "1817",
    howToPronounce: "KAD-mee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 49,
    symbol: "In",
    name: "Indium",
    atomicNumber: 49,
    position: { row: 5, col: 13 },
    category: "Post-transition Metal",
    atomicRadius: "167 pm",
    atomicWeight: "114.82 amu",
    density: "7.31 g/cm³",
    electroNegativity: "1.78",
    meltingPoint: "429.75 K",
    boilingPoint: "2345 K",
    standardState: "Solid",
    ionizationEnergy: "558 kJ/mol",
    discoveredBy: "Ferdinand Reich & Theodor Richter",
    discoveredYear: "1863",
    howToPronounce: "IN-dee-um",
    bg: "#331f1f",
    cardBG: "#241616",
    secondCardBG: "#331f1f",
    textColor: "#ff9a9a",
  },
  {
    index: 50,
    symbol: "Sn",
    name: "Tin",
    atomicNumber: 50,
    position: { row: 5, col: 14 },
    category: "Post-transition Metal",
    atomicRadius: "140 pm",
    atomicWeight: "118.71 amu",
    density: "7.29 g/cm³",
    electroNegativity: "1.96",
    meltingPoint: "505.08 K",
    boilingPoint: "2875 K",
    standardState: "Solid",
    ionizationEnergy: "709 kJ/mol",
    discoveredBy: "Ancient",
    discoveredYear: "unknown",
    howToPronounce: "TIN",
    bg: "#331f1f",
    cardBG: "#241616",
    secondCardBG: "#331f1f",
    textColor: "#ff9a9a",
  },
  {
    index: 51,
    symbol: "Sb",
    name: "Antimony",
    atomicNumber: 51,
    position: { row: 5, col: 15 },
    category: "Metalloid",
    atomicRadius: "141 pm",
    atomicWeight: "121.76 amu",
    density: "6.697 g/cm³",
    electroNegativity: "2.05",
    meltingPoint: "903.78 K",
    boilingPoint: "1860 K",
    standardState: "Solid",
    ionizationEnergy: "834 kJ/mol",
    discoveredBy: "Ancient",
    discoveredYear: "unknown",
    howToPronounce: "AN-ti-mo-nee",
    bg: "#23274d",
    cardBG: "#171a33",
    secondCardBG: "#23274d",
    textColor: "#a3abff",
  },
  {
    index: 52,
    symbol: "Te",
    name: "Tellurium",
    atomicNumber: 52,
    position: { row: 5, col: 16 },
    category: "Metalloid",
    atomicRadius: "140 pm",
    atomicWeight: "127.60 amu",
    density: "6.24 g/cm³",
    electroNegativity: "2.1",
    meltingPoint: "722.66 K",
    boilingPoint: "1261 K",
    standardState: "Solid",
    ionizationEnergy: "869 kJ/mol",
    discoveredBy: "Franz-Joseph Müller von Reichenstein",
    discoveredYear: "1782",
    howToPronounce: "teh-LOO-ree-um",
    bg: "#23274d",
    cardBG: "#171a33",
    secondCardBG: "#23274d",
    textColor: "#a3abff",
  },
  {
    index: 53,
    symbol: "I",
    name: "Iodine",
    atomicNumber: 53,
    position: { row: 5, col: 17 },
    category: "Halogen",
    atomicRadius: "133 pm",
    atomicWeight: "126.90 amu",
    density: "4.93 g/cm³",
    electroNegativity: "2.66",
    meltingPoint: "386.85 K",
    boilingPoint: "457.4 K",
    standardState: "Solid",
    ionizationEnergy: "1008 kJ/mol",
    discoveredBy: "Bernard Courtois",
    discoveredYear: "1811",
    howToPronounce: "EYE-oh-dine",
    bg: "#4d0044",
    cardBG: "#33002d",
    secondCardBG: "#4d0044",
    textColor: "#ff99f3",
  },
  {
    index: 54,
    symbol: "Xe",
    name: "Xenon",
    atomicNumber: 54,
    position: { row: 5, col: 18 },
    category: "Noble Gas",
    atomicRadius: "130 pm",
    atomicWeight: "131.29 amu",
    density: "0.005887 g/cm³",
    electroNegativity: "2.6",
    meltingPoint: "161.36 K",
    boilingPoint: "165.03 K",
    standardState: "Gas",
    ionizationEnergy: "1170 kJ/mol",
    discoveredBy: "William Ramsay & Morris Travers",
    discoveredYear: "1898",
    howToPronounce: "ZEE-non",
    bg: "#0e2b57",
    cardBG: "#0a1e3d",
    secondCardBG: "#0e2b57",
    textColor: "#87b7ff",
  },
  {
    index: 55,
    symbol: "Cs",
    name: "Cesium",
    atomicNumber: 55,
    position: { row: 6, col: 1 },
    category: "Alkali Metal",
    atomicRadius: "262 pm",
    atomicWeight: "132.91 amu",
    density: "1.93 g/cm³",
    electroNegativity: "0.79",
    meltingPoint: "301.59 K",
    boilingPoint: "944 K",
    standardState: "Solid",
    ionizationEnergy: "376 kJ/mol",
    discoveredBy: "Robert Bunsen & Gustav Kirchhoff",
    discoveredYear: "1860",
    howToPronounce: "SEE-zee-um",
    bg: "#3e204d",
    cardBG: "#2d1738",
    secondCardBG: "#3e204d",
    textColor: "#d582ff",
  },
  {
    index: 56,
    symbol: "Ba",
    name: "Barium",
    atomicNumber: 56,
    position: { row: 6, col: 2 },
    category: "Alkaline Earth Metal",
    atomicRadius: "253 pm",
    atomicWeight: "137.33 amu",
    density: "3.62 g/cm³",
    electroNegativity: "0.89",
    meltingPoint: "1000 K",
    boilingPoint: "2170 K",
    standardState: "Solid",
    ionizationEnergy: "503 kJ/mol",
    discoveredBy: "Carl Wilhelm Scheele",
    discoveredYear: "1772",
    howToPronounce: "BAIR-ee-um",
    bg: "#45434c",
    cardBG: "#45434c",
    secondCardBG: "#2e2d33",
    textColor: "#f6f4ff",
  },
  {
    name: "",
    index: 57,
    symbol: "57 to 71",
    bg: "#332c14",
    textColor: "#ffdd65",
    position: { row: 6, col: 3 },
  },
  {
    index: 72,
    symbol: "Hf",
    name: "Hafnium",
    atomicNumber: 72,
    position: { row: 6, col: 4 },
    category: "Transition Metal",
    atomicRadius: "159 pm",
    atomicWeight: "178.49 amu",
    density: "13.31 g/cm³",
    electroNegativity: "1.3",
    meltingPoint: "2506 K",
    boilingPoint: "4876 K",
    standardState: "Solid",
    ionizationEnergy: "659 kJ/mol",
    discoveredBy: "Dirk Coster & George de Hevesy",
    discoveredYear: "1923",
    howToPronounce: "HAF-nee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 73,
    symbol: "Ta",
    name: "Tantalum",
    atomicNumber: 73,
    position: { row: 6, col: 5 },
    category: "Transition Metal",
    atomicRadius: "146 pm",
    atomicWeight: "180.95 amu",
    density: "16.65 g/cm³",
    electroNegativity: "1.5",
    meltingPoint: "3290 K",
    boilingPoint: "5731 K",
    standardState: "Solid",
    ionizationEnergy: "761 kJ/mol",
    discoveredBy: "Anders Gustaf Ekeberg",
    discoveredYear: "1802",
    howToPronounce: "TAN-ta-lum",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 74,
    symbol: "W",
    name: "Tungsten",
    atomicNumber: 74,
    position: { row: 6, col: 6 },
    category: "Transition Metal",
    atomicRadius: "139 pm",
    atomicWeight: "183.84 amu",
    density: "19.25 g/cm³",
    electroNegativity: "2.36",
    meltingPoint: "3695 K",
    boilingPoint: "5828 K",
    standardState: "Solid",
    ionizationEnergy: "770 kJ/mol",
    discoveredBy: "Juan José & Fausto Elhuyar",
    discoveredYear: "1783",
    howToPronounce: "TUNG-sten",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 75,
    symbol: "Re",
    name: "Rhenium",
    atomicNumber: 75,
    position: { row: 6, col: 7 },
    category: "Transition Metal",
    atomicRadius: "137 pm",
    atomicWeight: "186.21 amu",
    density: "21.02 g/cm³",
    electroNegativity: "1.9",
    meltingPoint: "3459 K",
    boilingPoint: "5869 K",
    standardState: "Solid",
    ionizationEnergy: "760 kJ/mol",
    discoveredBy: "Ida Tacke, Walter Noddack & Otto Berg",
    discoveredYear: "1925",
    howToPronounce: "REE-nee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 76,
    symbol: "Os",
    name: "Osmium",
    atomicNumber: 76,
    position: { row: 6, col: 8 },
    category: "Transition Metal",
    atomicRadius: "135 pm",
    atomicWeight: "190.23 amu",
    density: "22.59 g/cm³",
    electroNegativity: "2.2",
    meltingPoint: "3306 K",
    boilingPoint: "5285 K",
    standardState: "Solid",
    ionizationEnergy: "840 kJ/mol",
    discoveredBy: "Smithson Tennant",
    discoveredYear: "1803",
    howToPronounce: "OZ-mee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 77,
    symbol: "Ir",
    name: "Iridium",
    atomicNumber: 77,
    position: { row: 6, col: 9 },
    category: "Transition Metal",
    atomicRadius: "136 pm",
    atomicWeight: "192.22 amu",
    density: "22.56 g/cm³",
    electroNegativity: "2.2",
    meltingPoint: "2719 K",
    boilingPoint: "4403 K",
    standardState: "Solid",
    ionizationEnergy: "880 kJ/mol",
    discoveredBy: "Smithson Tennant",
    discoveredYear: "1803",
    howToPronounce: "ih-RID-ee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 78,
    symbol: "Pt",
    name: "Platinum",
    atomicNumber: 78,
    position: { row: 6, col: 10 },
    category: "Transition Metal",
    atomicRadius: "139 pm",
    atomicWeight: "195.08 amu",
    density: "21.45 g/cm³",
    electroNegativity: "2.28",
    meltingPoint: "2041.4 K",
    boilingPoint: "4098 K",
    standardState: "Solid",
    ionizationEnergy: "870 kJ/mol",
    discoveredBy: "Antonio de Ulloa",
    discoveredYear: "1735",
    howToPronounce: "PLAT-in-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 79,
    symbol: "Au",
    name: "Gold",
    atomicNumber: 79,
    position: { row: 6, col: 11 },
    category: "Transition Metal",
    atomicRadius: "144 pm",
    atomicWeight: "196.97 amu",
    density: "19.30 g/cm³",
    electroNegativity: "2.54",
    meltingPoint: "1337.33 K",
    boilingPoint: "3129 K",
    standardState: "Solid",
    ionizationEnergy: "890 kJ/mol",
    discoveredBy: "Ancient",
    discoveredYear: "unknown",
    howToPronounce: "gold",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 80,
    symbol: "Hg",
    name: "Mercury",
    atomicNumber: 80,
    position: { row: 6, col: 12 },
    category: "Transition Metal",
    atomicRadius: "151 pm",
    atomicWeight: "200.59 amu",
    density: "13.53 g/cm³",
    electroNegativity: "2.00",
    meltingPoint: "234.32 K",
    boilingPoint: "629.88 K",
    standardState: "Liquid",
    ionizationEnergy: "1007 kJ/mol",
    discoveredBy: "Ancient",
    discoveredYear: "unknown",
    howToPronounce: "MER-kyoor-ee",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 81,
    symbol: "Tl",
    name: "Thallium",
    atomicNumber: 81,
    position: { row: 6, col: 13 },
    category: "Post-transition Metal",
    atomicRadius: "156 pm",
    atomicWeight: "204.38 amu",
    density: "11.85 g/cm³",
    electroNegativity: "1.62",
    meltingPoint: "577 K",
    boilingPoint: "1746 K",
    standardState: "Solid",
    ionizationEnergy: "589 kJ/mol",
    discoveredBy: "William Crookes",
    discoveredYear: "1861",
    howToPronounce: "THAL-ee-um",
    bg: "#331f1f",
    cardBG: "#241616",
    secondCardBG: "#331f1f",
    textColor: "#ff9a9a",
  },
  {
    index: 82,
    symbol: "Pb",
    name: "Lead",
    atomicNumber: 82,
    position: { row: 6, col: 14 },
    category: "Post-transition Metal",
    atomicRadius: "154 pm",
    atomicWeight: "207.2 amu",
    density: "11.34 g/cm³",
    electroNegativity: "2.33",
    meltingPoint: "601 K",
    boilingPoint: "2022 K",
    standardState: "Solid",
    ionizationEnergy: "716 kJ/mol",
    discoveredBy: "Prehistoric",
    discoveredYear: "unknown",
    howToPronounce: "LED",
    bg: "#331f1f",
    cardBG: "#241616",
    secondCardBG: "#331f1f",
    textColor: "#ff9a9a",
  },
  {
    index: 83,
    symbol: "Bi",
    name: "Bismuth",
    atomicNumber: 83,
    position: { row: 6, col: 15 },
    category: "Post-transition Metal",
    atomicRadius: "143 pm",
    atomicWeight: "208.980 amu",
    density: "9.78 g/cm³",
    electroNegativity: "2.02",
    meltingPoint: "544 K",
    boilingPoint: "1837 K",
    standardState: "Solid",
    ionizationEnergy: "703 kJ/mol",
    discoveredBy: "Claude François Geoffroy",
    discoveredYear: "1753",
    howToPronounce: "BIZ-muth",
    bg: "#331f1f",
    cardBG: "#241616",
    secondCardBG: "#331f1f",
    textColor: "#ff9a9a",
  },
  {
    index: 84,
    symbol: "Po",
    name: "Polonium",
    atomicNumber: 84,
    position: { row: 6, col: 16 },
    category: "Metalloid",
    atomicRadius: "135 pm",
    atomicWeight: "209 amu",
    density: "9.20 g/cm³",
    electroNegativity: "2.0",
    meltingPoint: "527 K",
    boilingPoint: "1235 K",
    standardState: "Solid",
    ionizationEnergy: "812 kJ/mol",
    discoveredBy: "Marie Curie, Pierre Curie",
    discoveredYear: "1898",
    howToPronounce: "po-LO-nee-um",
    bg: "#23274d",
    cardBG: "#171a33",
    secondCardBG: "#23274d",
    textColor: "#a3abff",
  },
  {
    index: 85,
    symbol: "At",
    name: "Astatine",
    atomicNumber: 85,
    position: { row: 6, col: 17 },
    category: "Halogen",
    atomicRadius: "127 pm",
    atomicWeight: "210 amu",
    density: "7 g/cm³",
    electroNegativity: "2.2",
    meltingPoint: "575 K",
    boilingPoint: "610 K",
    standardState: "Solid",
    ionizationEnergy: "920 kJ/mol",
    discoveredBy: "Dale R. Corson, Kenneth Ross MacKenzie, Emilio Segrè",
    discoveredYear: "1940",
    howToPronounce: "AS-ta-teen",
    bg: "#4d0044",
    cardBG: "#33002d",
    secondCardBG: "#4d0044",
    textColor: "#ff99f3",
  },
  {
    index: 86,
    symbol: "Rn",
    name: "Radon",
    atomicNumber: 86,
    position: { row: 6, col: 18 },
    category: "Noble Gas",
    atomicRadius: "120 pm",
    atomicWeight: "222 amu",
    density: "9.73 g/L",
    electroNegativity: "2.2",
    meltingPoint: "202 K",
    boilingPoint: "211 K",
    standardState: "Gas",
    ionizationEnergy: "1037 kJ/mol",
    discoveredBy: "Friedrich Ernst Dorn",
    discoveredYear: "1898",
    howToPronounce: "RAY-don",
    bg: "#0e2b57",
    cardBG: "#0a1e3d",
    secondCardBG: "#0e2b57",
    textColor: "#87b7ff",
  },
  {
    index: 87,
    symbol: "Fr",
    name: "Francium",
    atomicNumber: 87,
    position: { row: 7, col: 1 },
    category: "Alkali Metal",
    atomicRadius: "348 pm",
    atomicWeight: "223 amu",
    density: "1.87 g/cm³",
    electroNegativity: "0.7",
    meltingPoint: "300 K",
    boilingPoint: "950 K",
    standardState: "Solid",
    ionizationEnergy: "380 kJ/mol",
    discoveredBy: "Marguerite Perey",
    discoveredYear: "1939",
    howToPronounce: "FRAN-see-um",
    bg: "#3e204d",
    cardBG: "#2d1738",
    secondCardBG: "#3e204d",
    textColor: "#d582ff",
  },
  {
    index: 88,
    symbol: "Ra",
    name: "Radium",
    atomicNumber: 88,
    position: { row: 7, col: 2 },
    category: "Alkaline Earth Metal",
    atomicRadius: "283 pm",
    atomicWeight: "226 amu",
    density: "5.50 g/cm³",
    electroNegativity: "0.9",
    meltingPoint: "973 K",
    boilingPoint: "2010 K",
    standardState: "Solid",
    ionizationEnergy: "509 kJ/mol",
    discoveredBy: "Pierre Curie, Marie Curie",
    discoveredYear: "1898",
    howToPronounce: "RAY-dee-um",
    bg: "#45434c",
    cardBG: "#45434c",
    secondCardBG: "#2e2d33",
    textColor: "#f6f4ff",
  },
  {
    name: "",
    index: 89,
    symbol: "89 to 103",
    bg: "#001e33",
    textColor: "#66bfff",
    position: { row: 7, col: 3 },
  },
  {
    index: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    atomicNumber: 104,
    position: { row: 7, col: 4 },
    category: "Transition Metal",
    atomicRadius: "150 pm",
    atomicWeight: "267 amu",
    density: "23.2 g/cm³",
    electroNegativity: "unknown",
    meltingPoint: "2400 K",
    boilingPoint: "5800 K",
    standardState: "Solid",
    ionizationEnergy: "580 kJ/mol",
    discoveredBy:
      "Joint Institute for Nuclear Research, Dubna & Lawrence Berkeley Laboratory",
    discoveredYear: "1969",
    howToPronounce: "RUTH-er-ford-ee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 105,
    symbol: "Db",
    name: "Dubnium",
    atomicNumber: 105,
    position: { row: 7, col: 5 },
    category: "Transition Metal",
    atomicRadius: "139 pm",
    atomicWeight: "268 amu",
    density: "29.3 g/cm³",
    electroNegativity: "unknown",
    meltingPoint: "unknown",
    boilingPoint: "unknown",
    standardState: "Solid",
    ionizationEnergy: "665 kJ/mol",
    discoveredBy:
      "Joint Institute for Nuclear Research, Dubna & Lawrence Berkeley Laboratory",
    discoveredYear: "1967",
    howToPronounce: "DUB-nee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 106,
    symbol: "Sg",
    name: "Seaborgium",
    atomicNumber: 106,
    position: { row: 7, col: 6 },
    category: "Transition Metal",
    atomicRadius: "132 pm",
    atomicWeight: "271 amu",
    density: "35 g/cm³",
    electroNegativity: "unknown",
    meltingPoint: "unknown",
    boilingPoint: "unknown",
    standardState: "Solid",
    ionizationEnergy: "757 kJ/mol",
    discoveredBy: "Lawrence Berkeley Laboratory",
    discoveredYear: "1974",
    howToPronounce: "SEE-borg-ee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 107,
    symbol: "Bh",
    name: "Bohrium",
    atomicNumber: 107,
    position: { row: 7, col: 7 },
    category: "Transition Metal",
    atomicRadius: "128 pm",
    atomicWeight: "272 amu",
    density: "37.1 g/cm³",
    electroNegativity: "unknown",
    meltingPoint: "unknown",
    boilingPoint: "unknown",
    standardState: "Solid",
    ionizationEnergy: "740 kJ/mol",
    discoveredBy: "Gesellschaft für Schwerionenforschung (GSI), Darmstadt",
    discoveredYear: "1981",
    howToPronounce: "BOH-ree-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 108,
    symbol: "Hs",
    name: "Hassium",
    atomicNumber: 108,
    position: { row: 7, col: 8 },
    category: "Transition Metal",
    atomicRadius: "126 pm",
    atomicWeight: "270 amu",
    density: "41 g/cm³",
    electroNegativity: "unknown",
    meltingPoint: "unknown",
    boilingPoint: "unknown",
    standardState: "Solid",
    ionizationEnergy: "730 kJ/mol",
    discoveredBy: "Gesellschaft für Schwerionenforschung (GSI), Darmstadt",
    discoveredYear: "1984",
    howToPronounce: "HAS-ee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 109,
    symbol: "Mt",
    name: "Meitnerium",
    atomicNumber: 109,
    position: { row: 7, col: 9 },
    category: "Transition Metal",
    atomicRadius: "128 pm",
    atomicWeight: "278 amu",
    density: "37.4 g/cm³",
    electroNegativity: "unknown",
    meltingPoint: "unknown",
    boilingPoint: "unknown",
    standardState: "Solid",
    ionizationEnergy: "800 kJ/mol",
    discoveredBy: "Gesellschaft für Schwerionenforschung (GSI), Darmstadt",
    discoveredYear: "1982",
    howToPronounce: "MITE-ner-ee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    atomicNumber: 110,
    position: { row: 7, col: 10 },
    category: "Transition Metal",
    atomicRadius: "128 pm",
    atomicWeight: "281 amu",
    density: "34.8 g/cm³",
    electroNegativity: "unknown",
    meltingPoint: "unknown",
    boilingPoint: "unknown",
    standardState: "Solid",
    ionizationEnergy: "unknown",
    discoveredBy: "Gesellschaft für Schwerionenforschung (GSI), Darmstadt",
    discoveredYear: "1994",
    howToPronounce: "DARM-shtat-ee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 111,
    symbol: "Rg",
    name: "Roentgenium",
    atomicNumber: 111,
    position: { row: 7, col: 11 },
    category: "Transition Metal",
    atomicRadius: "121 pm",
    atomicWeight: "282 amu",
    density: "28.7 g/cm³",
    electroNegativity: "unknown",
    meltingPoint: "unknown",
    boilingPoint: "unknown",
    standardState: "Solid",
    ionizationEnergy: "1020 kJ/mol",
    discoveredBy: "Gesellschaft für Schwerionenforschung (GSI), Darmstadt",
    discoveredYear: "1994",
    howToPronounce: "RUNT-gen-ee-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 112,
    symbol: "Cn",
    name: "Copernicium",
    atomicNumber: 112,
    position: { row: 7, col: 12 },
    category: "Transition Metal",
    atomicRadius: "122 pm",
    atomicWeight: "285 amu",
    density: "14 g/cm³",
    electroNegativity: "unknown",
    meltingPoint: "357 K",
    boilingPoint: "1085 K",
    standardState: "Liquid",
    ionizationEnergy: "1155 kJ/mol",
    discoveredBy: "Gesellschaft für Schwerionenforschung (GSI), Darmstadt",
    discoveredYear: "1996",
    howToPronounce: "koh-PER-nee-see-um",
    bg: "#233323",
    cardBG: "#172117",
    secondCardBG: "#233323",
    textColor: "#a3eba1",
  },
  {
    index: 113,
    symbol: "Nh",
    name: "Nihonium",
    atomicNumber: 113,
    position: { row: 7, col: 13 },
    category: "Post-transition Metal",
    atomicRadius: "unknown",
    atomicWeight: "286 amu",
    density: "16 g/cm³",
    electroNegativity: "unknown",
    meltingPoint: "700 K",
    boilingPoint: "1400 K",
    standardState: "Solid",
    ionizationEnergy: "704 kJ/mol",
    discoveredBy: "RIKEN, Japan",
    discoveredYear: "2003",
    howToPronounce: "nee-HO-nee-um",
    bg: "#331f1f",
    cardBG: "#241616",
    secondCardBG: "#331f1f",
    textColor: "#ff9a9a",
  },
  {
    index: 114,
    symbol: "Fl",
    name: "Flerovium",
    atomicNumber: 114,
    position: { row: 7, col: 14 },
    category: "Post-transition Metal",
    atomicRadius: "unknown",
    atomicWeight: "289 amu",
    density: "14 g/cm³",
    electroNegativity: "unknown",
    meltingPoint: "340 K",
    boilingPoint: "420 K",
    standardState: "Solid",
    ionizationEnergy: "823 kJ/mol",
    discoveredBy: "Joint Institute for Nuclear Research, Dubna",
    discoveredYear: "1998",
    howToPronounce: "fleh-ROH-vee-um",
    bg: "#331f1f",
    cardBG: "#241616",
    secondCardBG: "#331f1f",
    textColor: "#ff9a9a",
  },
  {
    index: 115,
    symbol: "Mc",
    name: "Moscovium",
    atomicNumber: 115,
    position: { row: 7, col: 15 },
    category: "Post-transition Metal",
    atomicRadius: "unknown",
    atomicWeight: "290 amu",
    density: "13.5 g/cm³",
    electroNegativity: "unknown",
    meltingPoint: "670 K",
    boilingPoint: "1400 K",
    standardState: "Solid",
    ionizationEnergy: "538 kJ/mol",
    discoveredBy:
      "Joint Institute for Nuclear Research, Dubna & Lawrence Livermore National Laboratory",
    discoveredYear: "2003",
    howToPronounce: "mos-KOH-vee-um",
    bg: "#331f1f",
    cardBG: "#241616",
    secondCardBG: "#331f1f",
    textColor: "#ff9a9a",
  },
  {
    index: 116,
    symbol: "Lv",
    name: "Livermorium",
    atomicNumber: 116,
    position: { row: 7, col: 16 },
    category: "Post-transition Metal",
    atomicRadius: "unknown",
    atomicWeight: "293 amu",
    density: "12.9 g/cm³",
    electroNegativity: "unknown",
    meltingPoint: "709 K",
    boilingPoint: "1085 K",
    standardState: "Solid",
    ionizationEnergy: "663 kJ/mol",
    discoveredBy:
      "Joint Institute for Nuclear Research, Dubna & Lawrence Livermore National Laboratory",
    discoveredYear: "2000",
    howToPronounce: "LIV-er-mor-ee-um",
    bg: "#331f1f",
    cardBG: "#241616",
    secondCardBG: "#331f1f",
    textColor: "#ff9a9a",
  },
  {
    index: 117,
    symbol: "Ts",
    name: "Tennessine",
    atomicNumber: 117,
    position: { row: 7, col: 17 },
    category: "Halogen",
    atomicRadius: "unknown",
    atomicWeight: "294 amu",
    density: "7.2 g/cm³",
    electroNegativity: "unknown",
    meltingPoint: "723 K",
    boilingPoint: "883 K",
    standardState: "Solid",
    ionizationEnergy: "742 kJ/mol",
    discoveredBy:
      "Joint Institute for Nuclear Research, Dubna & Oak Ridge National Laboratory",
    discoveredYear: "2010",
    howToPronounce: "TEN-uh-seen",
    bg: "#4d0044",
    cardBG: "#33002d",
    secondCardBG: "#4d0044",
    textColor: "#ff99f3",
  },
  {
    index: 118,
    symbol: "Og",
    name: "Oganesson",
    atomicNumber: 118,
    position: { row: 7, col: 18 },
    category: "Noble Gas",
    atomicRadius: "152 pm",
    atomicWeight: "294 amu",
    density: "4.9 g/L",
    electroNegativity: "unknown",
    meltingPoint: "350 K",
    boilingPoint: "450 K",
    standardState: "Gas",
    ionizationEnergy: "860 kJ/mol",
    discoveredBy:
      "Joint Institute for Nuclear Research, Dubna & Lawrence Livermore National Laboratory",
    discoveredYear: "2002",
    howToPronounce: "oh-gah-NESS-on",
    bg: "#0e2b57",
    cardBG: "#0a1e3d",
    secondCardBG: "#0e2b57",
    textColor: "#87b7ff",
  },
];

export const lanthanideElements = [
  {
    index: 57,
    symbol: "La",
    name: "Lanthanum",
    atomicNumber: 57,
    position: { row: 6, col: 3 },
    category: "Lanthanide",
    atomicRadius: "195 pm",
    atomicWeight: "138.91 amu",
    density: "6.15 g/cm³",
    electroNegativity: "1.10",
    meltingPoint: "1193 K",
    boilingPoint: "3737 K",
    standardState: "Solid",
    ionizationEnergy: "538 kJ/mol",
    discoveredBy: "Carl Gustaf Mosander",
    discoveredYear: "1839",
    howToPronounce: "LAN-tha-num",
    bg: "#332c14",
    cardBG: "#241f0e",
    secondCardBG: "#332c14",
    textColor: "#ffdd65",
  },
  {
    index: 58,
    symbol: "Ce",
    name: "Cerium",
    atomicNumber: 58,
    position: { row: 6, col: 4 },
    category: "Lanthanide",
    atomicRadius: "185 pm",
    atomicWeight: "140.12 amu",
    density: "6.770 g/cm³",
    electroNegativity: "1.12",
    meltingPoint: "1068 K",
    boilingPoint: "3716 K",
    standardState: "Solid",
    ionizationEnergy: "534 kJ/mol",
    discoveredBy: "Martin Heinrich Klaproth",
    discoveredYear: "1803",
    howToPronounce: "SEER-ee-um",
    bg: "#332c14",
    cardBG: "#241f0e",
    secondCardBG: "#332c14",
    textColor: "#ffdd65",
  },
  {
    index: 59,
    symbol: "Pr",
    name: "Praseodymium",
    atomicNumber: 59,
    position: { row: 6, col: 5 },
    category: "Lanthanide",
    atomicRadius: "185 pm",
    atomicWeight: "140.91 amu",
    density: "6.77 g/cm³",
    electroNegativity: "1.13",
    meltingPoint: "1208 K",
    boilingPoint: "3793 K",
    standardState: "Solid",
    ionizationEnergy: "527 kJ/mol",
    discoveredBy: "Carl Auer von Welsbach",
    discoveredYear: "1885",
    howToPronounce: "PRAY-zee-oh-DIM-ee-um",
    bg: "#332c14",
    cardBG: "#241f0e",
    secondCardBG: "#332c14",
    textColor: "#ffdd65",
  },
  {
    index: 60,
    symbol: "Nd",
    name: "Neodymium",
    atomicNumber: 60,
    position: { row: 6, col: 6 },
    category: "Lanthanide",
    atomicRadius: "185 pm",
    atomicWeight: "144.24 amu",
    density: "7.01 g/cm³",
    electroNegativity: "1.14",
    meltingPoint: "1297 K",
    boilingPoint: "3347 K",
    standardState: "Solid",
    ionizationEnergy: "533 kJ/mol",
    discoveredBy: "Carl Auer von Welsbach",
    discoveredYear: "1885",
    howToPronounce: "nee-oh-DIM-ee-um",
    bg: "#332c14",
    cardBG: "#241f0e",
    secondCardBG: "#332c14",
    textColor: "#ffdd65",
  },
  {
    index: 61,
    symbol: "Pm",
    name: "Promethium",
    atomicNumber: 61,
    position: { row: 6, col: 7 },
    category: "Lanthanide",
    atomicRadius: "183 pm",
    atomicWeight: "145 amu",
    density: "7.26 g/cm³",
    electroNegativity: "0",
    meltingPoint: "1315 K",
    boilingPoint: "3273 K",
    standardState: "Solid",
    ionizationEnergy: "540 kJ/mol",
    discoveredBy: "Chien Shiung Wu & Emilio Segrè",
    discoveredYear: "1945",
    howToPronounce: "pro-MEE-thee-um",
    bg: "#332c14",
    cardBG: "#241f0e",
    secondCardBG: "#332c14",
    textColor: "#ffdd65",
  },
  {
    index: 62,
    symbol: "Sm",
    name: "Samarium",
    atomicNumber: 62,
    position: { row: 6, col: 8 },
    category: "Lanthanide",
    atomicRadius: "180 pm",
    atomicWeight: "150.36 amu",
    density: "7.52 g/cm³",
    electroNegativity: "1.17",
    meltingPoint: "1345 K",
    boilingPoint: "2067 K",
    standardState: "Solid",
    ionizationEnergy: "544 kJ/mol",
    discoveredBy: "Paul Émile Lecoq de Boisbaudran",
    discoveredYear: "1879",
    howToPronounce: "sa-MARE-ee-um",
    bg: "#332c14",
    cardBG: "#241f0e",
    secondCardBG: "#332c14",
    textColor: "#ffdd65",
  },
  {
    index: 63,
    symbol: "Eu",
    name: "Europium",
    atomicNumber: 63,
    position: { row: 6, col: 9 },
    category: "Lanthanide",
    atomicRadius: "199 pm",
    atomicWeight: "151.96 amu",
    density: "5.24 g/cm³",
    electroNegativity: "0",
    meltingPoint: "1099 K",
    boilingPoint: "1802 K",
    standardState: "Solid",
    ionizationEnergy: "547 kJ/mol",
    discoveredBy: "Eugène-Anatole Demarçay",
    discoveredYear: "1901",
    howToPronounce: "yoo-RO-pee-um",
    bg: "#332c14",
    cardBG: "#241f0e",
    secondCardBG: "#332c14",
    textColor: "#ffdd65",
  },
  {
    index: 64,
    symbol: "Gd",
    name: "Gadolinium",
    atomicNumber: 64,
    position: { row: 6, col: 10 },
    category: "Lanthanide",
    atomicRadius: "179 pm",
    atomicWeight: "157.25 amu",
    density: "7.90 g/cm³",
    electroNegativity: "1.20",
    meltingPoint: "1586 K",
    boilingPoint: "3546 K",
    standardState: "Solid",
    ionizationEnergy: "593 kJ/mol",
    discoveredBy: "Jean Charles Galissard de Marignac",
    discoveredYear: "1880",
    howToPronounce: "gad-o-LIN-ee-um",
    bg: "#332c14",
    cardBG: "#241f0e",
    secondCardBG: "#332c14",
    textColor: "#ffdd65",
  },
  {
    index: 65,
    symbol: "Tb",
    name: "Terbium",
    atomicNumber: 65,
    position: { row: 6, col: 11 },
    category: "Lanthanide",
    atomicRadius: "177 pm",
    atomicWeight: "158.93 amu",
    density: "8.23 g/cm³",
    electroNegativity: "1.20",
    meltingPoint: "1629 K",
    boilingPoint: "3503 K",
    standardState: "Solid",
    ionizationEnergy: "566 kJ/mol",
    discoveredBy: "Carl Gustaf Mosander",
    discoveredYear: "1843",
    howToPronounce: "TER-bee-um",
    bg: "#332c14",
    cardBG: "#241f0e",
    secondCardBG: "#332c14",
    textColor: "#ffdd65",
  },
  {
    index: 66,
    symbol: "Dy",
    name: "Dysprosium",
    atomicNumber: 66,
    position: { row: 6, col: 12 },
    category: "Lanthanide",
    atomicRadius: "178 pm",
    atomicWeight: "162.50 amu",
    density: "8.54 g/cm³",
    electroNegativity: "1.22",
    meltingPoint: "1680 K",
    boilingPoint: "2840 K",
    standardState: "Solid",
    ionizationEnergy: "573 kJ/mol",
    discoveredBy: "Paul Émile Lecoq de Boisbaudran",
    discoveredYear: "1886",
    howToPronounce: "dis-PRO-zee-um",
    bg: "#332c14",
    cardBG: "#241f0e",
    secondCardBG: "#332c14",
    textColor: "#ffdd65",
  },
  {
    index: 67,
    symbol: "Ho",
    name: "Holmium",
    atomicNumber: 67,
    position: { row: 6, col: 13 },
    category: "Lanthanide",
    atomicRadius: "176 pm",
    atomicWeight: "164.93 amu",
    density: "8.79 g/cm³",
    electroNegativity: "1.23",
    meltingPoint: "1747 K",
    boilingPoint: "2973 K",
    standardState: "Solid",
    ionizationEnergy: "581 kJ/mol",
    discoveredBy: "Marc Delafontaine & Jacques-Louis Soret",
    discoveredYear: "1878",
    howToPronounce: "HOL-mee-um",
    bg: "#332c14",
    cardBG: "#241f0e",
    secondCardBG: "#332c14",
    textColor: "#ffdd65",
  },
  {
    index: 68,
    symbol: "Er",
    name: "Erbium",
    atomicNumber: 68,
    position: { row: 6, col: 14 },
    category: "Lanthanide",
    atomicRadius: "176 pm",
    atomicWeight: "167.26 amu",
    density: "9.07 g/cm³",
    electroNegativity: "1.24",
    meltingPoint: "1802 K",
    boilingPoint: "3141 K",
    standardState: "Solid",
    ionizationEnergy: "589 kJ/mol",
    discoveredBy: "Carl Gustaf Mosander",
    discoveredYear: "1843",
    howToPronounce: "UR-bee-um",
    bg: "#332c14",
    cardBG: "#241f0e",
    secondCardBG: "#332c14",
    textColor: "#ffdd65",
  },
  {
    index: 69,
    symbol: "Tm",
    name: "Thulium",
    atomicNumber: 69,
    position: { row: 6, col: 15 },
    category: "Lanthanide",
    atomicRadius: "175 pm",
    atomicWeight: "168.93 amu",
    density: "9.32 g/cm³",
    electroNegativity: "1.25",
    meltingPoint: "1818 K",
    boilingPoint: "2223 K",
    standardState: "Solid",
    ionizationEnergy: "597 kJ/mol",
    discoveredBy: "Per Teodor Cleve",
    discoveredYear: "1879",
    howToPronounce: "THOO-lee-um",
    bg: "#332c14",
    cardBG: "#241f0e",
    secondCardBG: "#332c14",
    textColor: "#ffdd65",
  },
  {
    index: 70,
    symbol: "Yb",
    name: "Ytterbium",
    atomicNumber: 70,
    position: { row: 6, col: 16 },
    category: "Lanthanide",
    atomicRadius: "187 pm",
    atomicWeight: "173.05 amu",
    density: "6.90 g/cm³",
    electroNegativity: "0",
    meltingPoint: "1097 K",
    boilingPoint: "1469 K",
    standardState: "Solid",
    ionizationEnergy: "603 kJ/mol",
    discoveredBy: "Jean Charles Galissard de Marignac",
    discoveredYear: "1878",
    howToPronounce: "ih-TER-bee-um",
    bg: "#332c14",
    cardBG: "#241f0e",
    secondCardBG: "#332c14",
    textColor: "#ffdd65",
  },
  {
    index: 71,
    symbol: "Lu",
    name: "Lutetium",
    atomicNumber: 71,
    position: { row: 6, col: 17 },
    category: "Lanthanide",
    atomicRadius: "174 pm",
    atomicWeight: "174.97 amu",
    density: "9.84 g/cm³",
    electroNegativity: "1.27",
    meltingPoint: "1925 K",
    boilingPoint: "3675 K",
    standardState: "Solid",
    ionizationEnergy: "524 kJ/mol",
    discoveredBy: "Georges Urbain",
    discoveredYear: "1907",
    howToPronounce: "LOO-shee-um",
    bg: "#332c14",
    cardBG: "#241f0e",
    secondCardBG: "#332c14",
    textColor: "#ffdd65",
  },
];

export const actinideElements = [
  {
    index: 89,
    symbol: "Ac",
    name: "Actinium",
    atomicNumber: 89,
    position: { row: 7, col: 3 },
    category: "Actinide",
    atomicRadius: "260 pm",
    atomicWeight: "227 amu",
    density: "10.07 g/cm³",
    electroNegativity: "1.1",
    meltingPoint: "1323 K",
    boilingPoint: "3471 K",
    standardState: "Solid",
    ionizationEnergy: "499 kJ/mol",
    discoveredBy: "Friedrich Oskar Giesel",
    discoveredYear: "1899",
    howToPronounce: "ak-TIN-ee-um",
    bg: "#001e33",
    cardBG: "#001321",
    secondCardBG: "#001e33",
    textColor: "#66bfff",
  },
  {
    index: 90,
    symbol: "Th",
    name: "Thorium",
    atomicNumber: 90,
    position: { row: 7, col: 4 },
    category: "Actinide",
    atomicRadius: "237 pm",
    atomicWeight: "232.037 amu",
    density: "11.72 g/cm³",
    electroNegativity: "1.3",
    meltingPoint: "2115 K",
    boilingPoint: "5061 K",
    standardState: "Solid",
    ionizationEnergy: "587 kJ/mol",
    discoveredBy: "Jöns Jacob Berzelius",
    discoveredYear: "1829",
    howToPronounce: "THOR-ee-um",
    bg: "#001e33",
    cardBG: "#001321",
    secondCardBG: "#001e33",
    textColor: "#66bfff",
  },
  {
    index: 91,
    symbol: "Pa",
    name: "Protactinium",
    atomicNumber: 91,
    position: { row: 7, col: 5 },
    category: "Actinide",
    atomicRadius: "243 pm",
    atomicWeight: "231.035 amu",
    density: "15.37 g/cm³",
    electroNegativity: "1.5",
    meltingPoint: "1841 K",
    boilingPoint: "4300 K",
    standardState: "Solid",
    ionizationEnergy: "568 kJ/mol",
    discoveredBy: "Kasimir Fajans, Oswald Helmuth Göhring",
    discoveredYear: "1913",
    howToPronounce: "pro-TAK-tin-ee-um",
    bg: "#001e33",
    cardBG: "#001321",
    secondCardBG: "#001e33",
    textColor: "#66bfff",
  },
  {
    index: 92,
    symbol: "U",
    name: "Uranium",
    atomicNumber: 92,
    position: { row: 7, col: 6 },
    category: "Actinide",
    atomicRadius: "240 pm",
    atomicWeight: "238.0289 amu",
    density: "18.95 g/cm³",
    electroNegativity: "1.38",
    meltingPoint: "1405 K",
    boilingPoint: "4404 K",
    standardState: "Solid",
    ionizationEnergy: "597 kJ/mol",
    discoveredBy: "Martin Heinrich Klaproth",
    discoveredYear: "1789",
    howToPronounce: "yoo-RAY-nee-um",
    bg: "#001e33",
    cardBG: "#001321",
    secondCardBG: "#001e33",
    textColor: "#66bfff",
  },
  {
    index: 93,
    symbol: "Np",
    name: "Neptunium",
    atomicNumber: 93,
    position: { row: 7, col: 7 },
    category: "Actinide",
    atomicRadius: "221 pm",
    atomicWeight: "237 amu",
    density: "20.45 g/cm³",
    electroNegativity: "1.36",
    meltingPoint: "917 K",
    boilingPoint: "4273 K",
    standardState: "Solid",
    ionizationEnergy: "604 kJ/mol",
    discoveredBy: "Edwin McMillan, Philip H. Abelson",
    discoveredYear: "1940",
    howToPronounce: "NEP-too-nee-um",
    bg: "#001e33",
    cardBG: "#001321",
    secondCardBG: "#001e33",
    textColor: "#66bfff",
  },
  {
    index: 94,
    symbol: "Pu",
    name: "Plutonium",
    atomicNumber: 94,
    position: { row: 7, col: 8 },
    category: "Actinide",
    atomicRadius: "243 pm",
    atomicWeight: "244 amu",
    density: "19.84 g/cm³",
    electroNegativity: "1.28",
    meltingPoint: "913 K",
    boilingPoint: "3505 K",
    standardState: "Solid",
    ionizationEnergy: "585 kJ/mol",
    discoveredBy:
      "Glenn T. Seaborg, Edwin McMillan, Joseph W. Kennedy, Arthur Wahl",
    discoveredYear: "1940",
    howToPronounce: "ploo-TOH-nee-um",
    bg: "#001e33",
    cardBG: "#001321",
    secondCardBG: "#001e33",
    textColor: "#66bfff",
  },
  {
    index: 95,
    symbol: "Am",
    name: "Americium",
    atomicNumber: 95,
    position: { row: 7, col: 9 },
    category: "Actinide",
    atomicRadius: "244 pm",
    atomicWeight: "243 amu",
    density: "12 g/cm³",
    electroNegativity: "1.3",
    meltingPoint: "1449 K",
    boilingPoint: "2880 K",
    standardState: "Solid",
    ionizationEnergy: "578 kJ/mol",
    discoveredBy:
      "Glenn T. Seaborg, Ralph A. James, Leon O. Morgan, Albert Ghiorso",
    discoveredYear: "1944",
    howToPronounce: "am-uh-REE-see-um",
    bg: "#001e33",
    cardBG: "#001321",
    secondCardBG: "#001e33",
    textColor: "#66bfff",
  },
  {
    index: 96,
    symbol: "Cm",
    name: "Curium",
    atomicNumber: 96,
    position: { row: 7, col: 10 },
    category: "Actinide",
    atomicRadius: "245 pm",
    atomicWeight: "247 amu",
    density: "13.51 g/cm³",
    electroNegativity: "1.3",
    meltingPoint: "1613 K",
    boilingPoint: "3383 K",
    standardState: "Solid",
    ionizationEnergy: "581 kJ/mol",
    discoveredBy: "Glenn T. Seaborg, Ralph A. James, Albert Ghiorso",
    discoveredYear: "1944",
    howToPronounce: "KYUR-ee-um",
    bg: "#001e33",
    cardBG: "#001321",
    secondCardBG: "#001e33",
    textColor: "#66bfff",
  },
  {
    index: 97,
    symbol: "Bk",
    name: "Berkelium",
    atomicNumber: 97,
    position: { row: 7, col: 11 },
    category: "Actinide",
    atomicRadius: "244 pm",
    atomicWeight: "247 amu",
    density: "14.78 g/cm³",
    electroNegativity: "1.3",
    meltingPoint: "1259 K",
    boilingPoint: "2900 K",
    standardState: "Solid",
    ionizationEnergy: "601 kJ/mol",
    discoveredBy: "Stanley G. Thompson, Albert Ghiorso, Glenn T. Seaborg",
    discoveredYear: "1949",
    howToPronounce: "BURK-lee-um",
    bg: "#001e33",
    cardBG: "#001321",
    secondCardBG: "#001e33",
    textColor: "#66bfff",
  },
  {
    index: 98,
    symbol: "Cf",
    name: "Californium",
    atomicNumber: 98,
    position: { row: 7, col: 12 },
    category: "Actinide",
    atomicRadius: "245 pm",
    atomicWeight: "251 amu",
    density: "15.1 g/cm³",
    electroNegativity: "1.3",
    meltingPoint: "1173 K",
    boilingPoint: "1743 K",
    standardState: "Solid",
    ionizationEnergy: "608 kJ/mol",
    discoveredBy:
      "Stanley G. Thompson, Kenneth Street Jr., Albert Ghiorso, Glenn T. Seaborg",
    discoveredYear: "1950",
    howToPronounce: "kal-ih-FOR-nee-um",
    bg: "#001e33",
    cardBG: "#001321",
    secondCardBG: "#001e33",
    textColor: "#66bfff",
  },
  {
    index: 99,
    symbol: "Es",
    name: "Einsteinium",
    atomicNumber: 99,
    position: { row: 7, col: 13 },
    category: "Actinide",
    atomicRadius: "245 pm",
    atomicWeight: "252 amu",
    density: "8.84 g/cm³",
    electroNegativity: "1.3",
    meltingPoint: "1133 K",
    boilingPoint: "unknown",
    standardState: "Solid",
    ionizationEnergy: "619 kJ/mol",
    discoveredBy: "Albert Ghiorso and team",
    discoveredYear: "1952",
    howToPronounce: "INE-stine-ee-um",
    bg: "#001e33",
    cardBG: "#001321",
    secondCardBG: "#001e33",
    textColor: "#66bfff",
  },
  {
    index: 100,
    symbol: "Fm",
    name: "Fermium",
    atomicNumber: 100,
    position: { row: 7, col: 14 },
    category: "Actinide",
    atomicRadius: "245 pm",
    atomicWeight: "257 amu",
    density: "unknown",
    electroNegativity: "1.3",
    meltingPoint: "1800 K",
    boilingPoint: "unknown",
    standardState: "Solid",
    ionizationEnergy: "627 kJ/mol",
    discoveredBy: "Albert Ghiorso and team",
    discoveredYear: "1952",
    howToPronounce: "FUR-mee-um",
    bg: "#001e33",
    cardBG: "#001321",
    secondCardBG: "#001e33",
    textColor: "#66bfff",
  },
  {
    index: 101,
    symbol: "Md",
    name: "Mendelevium",
    atomicNumber: 101,
    position: { row: 7, col: 15 },
    category: "Actinide",
    atomicRadius: "246 pm",
    atomicWeight: "258 amu",
    density: "unknown",
    electroNegativity: "1.3",
    meltingPoint: "1100 K",
    boilingPoint: "unknown",
    standardState: "Solid",
    ionizationEnergy: "635 kJ/mol",
    discoveredBy:
      "Albert Ghiorso, Glenn T. Seaborg, Bernard Harvey, Gregory Choppin, Stanley G. Thompson",
    discoveredYear: "1955",
    howToPronounce: "men-duh-LEE-vee-um",
    bg: "#001e33",
    cardBG: "#001321",
    secondCardBG: "#001e33",
    textColor: "#66bfff",
  },
  {
    index: 102,
    symbol: "No",
    name: "Nobelium",
    atomicNumber: 102,
    position: { row: 7, col: 16 },
    category: "Actinide",
    atomicRadius: "246 pm",
    atomicWeight: "259 amu",
    density: "unknown",
    electroNegativity: "1.3",
    meltingPoint: "1100 K",
    boilingPoint: "unknown",
    standardState: "Solid",
    ionizationEnergy: "642 kJ/mol",
    discoveredBy: "Joint Institute for Nuclear Research, Dubna",
    discoveredYear: "1966",
    howToPronounce: "no-BEE-lee-um",
    bg: "#001e33",
    cardBG: "#001321",
    secondCardBG: "#001e33",
    textColor: "#66bfff",
  },
  {
    index: 103,
    symbol: "Lr",
    name: "Lawrencium",
    atomicNumber: 103,
    position: { row: 7, col: 17 },
    category: "Actinide",
    atomicRadius: "246 pm",
    atomicWeight: "266 amu",
    density: "unknown",
    electroNegativity: "1.3",
    meltingPoint: "1900 K",
    boilingPoint: "unknown",
    standardState: "Solid",
    ionizationEnergy: "470 kJ/mol",
    discoveredBy:
      "Joint Institute for Nuclear Research, Dubna & Lawrence Berkeley Laboratory",
    discoveredYear: "1961",
    howToPronounce: "lor-EN-see-um",
    bg: "#001e33",
    cardBG: "#001321",
    secondCardBG: "#001e33",
    textColor: "#66bfff",
  },
];
