const actinideElements = [
    {
  index: 89,
  symbol: "Ac",
  name: "Actinium",
  atomicNumber: 89,
  position: { row: 7, col: 3 },
  category: "Actinide",
  atomicRadius: "260 pm",
  atomicWeight: "227 amu",
  density: "10.07 g/cm³",
  electroNegativity: "1.1",
  meltingPoint: "1323 K",
  boilingPoint: "3471 K",
  standardState: "Solid",
  ionizationEnergy: "499 kJ/mol",
  discoveredBy: "Friedrich Oskar Giesel",
  discoveredYear: "1899",
  howToPronounce: "ak-TIN-ee-um"
},
{
  index: 90,
  symbol: "Th",
  name: "Thorium",
  atomicNumber: 90,
  position: { row: 7, col: 4 },
  category: "Actinide",
  atomicRadius: "237 pm",
  atomicWeight: "232.037 amu",
  density: "11.72 g/cm³",
  electroNegativity: "1.3",
  meltingPoint: "2115 K",
  boilingPoint: "5061 K",
  standardState: "Solid",
  ionizationEnergy: "587 kJ/mol",
  discoveredBy: "Jöns Jacob Berzelius",
  discoveredYear: "1829",
  howToPronounce: "THOR-ee-um"
},
{
  index: 91,
  symbol: "Pa",
  name: "Protactinium",
  atomicNumber: 91,
  position: { row: 7, col: 5 },
  category: "Actinide",
  atomicRadius: "243 pm",
  atomicWeight: "231.035 amu",
  density: "15.37 g/cm³",
  electroNegativity: "1.5",
  meltingPoint: "1841 K",
  boilingPoint: "4300 K",
  standardState: "Solid",
  ionizationEnergy: "568 kJ/mol",
  discoveredBy: "Kasimir Fajans, Oswald Helmuth Göhring",
  discoveredYear: "1913",
  howToPronounce: "pro-TAK-tin-ee-um"
},
{
  index: 92,
  symbol: "U",
  name: "Uranium",
  atomicNumber: 92,
  position: { row: 7, col: 6 },
  category: "Actinide",
  atomicRadius: "240 pm",
  atomicWeight: "238.0289 amu",
  density: "18.95 g/cm³",
  electroNegativity: "1.38",
  meltingPoint: "1405 K",
  boilingPoint: "4404 K",
  standardState: "Solid",
  ionizationEnergy: "597 kJ/mol",
  discoveredBy: "Martin Heinrich Klaproth",
  discoveredYear: "1789",
  howToPronounce: "yoo-RAY-nee-um"
},
{
  index: 93,
  symbol: "Np",
  name: "Neptunium",
  atomicNumber: 93,
  position: { row: 7, col: 7 },
  category: "Actinide",
  atomicRadius: "221 pm",
  atomicWeight: "237 amu",
  density: "20.45 g/cm³",
  electroNegativity: "1.36",
  meltingPoint: "917 K",
  boilingPoint: "4273 K",
  standardState: "Solid",
  ionizationEnergy: "604 kJ/mol",
  discoveredBy: "Edwin McMillan, Philip H. Abelson",
  discoveredYear: "1940",
  howToPronounce: "NEP-too-nee-um"
},
{
  index: 94,
  symbol: "Pu",
  name: "Plutonium",
  atomicNumber: 94,
  position: { row: 7, col: 8 },
  category: "Actinide",
  atomicRadius: "243 pm",
  atomicWeight: "244 amu",
  density: "19.84 g/cm³",
  electroNegativity: "1.28",
  meltingPoint: "913 K",
  boilingPoint: "3505 K",
  standardState: "Solid",
  ionizationEnergy: "585 kJ/mol",
  discoveredBy: "Glenn T. Seaborg, Edwin McMillan, Joseph W. Kennedy, Arthur Wahl",
  discoveredYear: "1940",
  howToPronounce: "ploo-TOH-nee-um"
},
{
  index: 95,
  symbol: "Am",
  name: "Americium",
  atomicNumber: 95,
  position: { row: 7, col: 9 },
  category: "Actinide",
  atomicRadius: "244 pm",
  atomicWeight: "243 amu",
  density: "12 g/cm³",
  electroNegativity: "1.3",
  meltingPoint: "1449 K",
  boilingPoint: "2880 K",
  standardState: "Solid",
  ionizationEnergy: "578 kJ/mol",
  discoveredBy: "Glenn T. Seaborg, Ralph A. James, Leon O. Morgan, Albert Ghiorso",
  discoveredYear: "1944",
  howToPronounce: "am-uh-REE-see-um"
},
{
  index: 96,
  symbol: "Cm",
  name: "Curium",
  atomicNumber: 96,
  position: { row: 7, col: 10 },
  category: "Actinide",
  atomicRadius: "245 pm",
  atomicWeight: "247 amu",
  density: "13.51 g/cm³",
  electroNegativity: "1.3",
  meltingPoint: "1613 K",
  boilingPoint: "3383 K",
  standardState: "Solid",
  ionizationEnergy: "581 kJ/mol",
  discoveredBy: "Glenn T. Seaborg, Ralph A. James, Albert Ghiorso",
  discoveredYear: "1944",
  howToPronounce: "KYUR-ee-um"
},
{
  index: 97,
  symbol: "Bk",
  name: "Berkelium",
  atomicNumber: 97,
  position: { row: 7, col: 11 },
  category: "Actinide",
  atomicRadius: "244 pm",
  atomicWeight: "247 amu",
  density: "14.78 g/cm³",
  electroNegativity: "1.3",
  meltingPoint: "1259 K",
  boilingPoint: "2900 K",
  standardState: "Solid",
  ionizationEnergy: "601 kJ/mol",
  discoveredBy: "Stanley G. Thompson, Albert Ghiorso, Glenn T. Seaborg",
  discoveredYear: "1949",
  howToPronounce: "BURK-lee-um"
},
{
  index: 98,
  symbol: "Cf",
  name: "Californium",
  atomicNumber: 98,
  position: { row: 7, col: 12 },
  category: "Actinide",
  atomicRadius: "245 pm",
  atomicWeight: "251 amu",
  density: "15.1 g/cm³",
  electroNegativity: "1.3",
  meltingPoint: "1173 K",
  boilingPoint: "1743 K",
  standardState: "Solid",
  ionizationEnergy: "608 kJ/mol",
  discoveredBy: "Stanley G. Thompson, Kenneth Street Jr., Albert Ghiorso, Glenn T. Seaborg",
  discoveredYear: "1950",
  howToPronounce: "kal-ih-FOR-nee-um"
},
{
  index: 99,
  symbol: "Es",
  name: "Einsteinium",
  atomicNumber: 99,
  position: { row: 7, col: 13 },
  category: "Actinide",
  atomicRadius: "245 pm",
  atomicWeight: "252 amu",
  density: "8.84 g/cm³",
  electroNegativity: "1.3",
  meltingPoint: "1133 K",
  boilingPoint: "unknown",
  standardState: "Solid",
  ionizationEnergy: "619 kJ/mol",
  discoveredBy: "Albert Ghiorso and team",
  discoveredYear: "1952",
  howToPronounce: "INE-stine-ee-um"
},
{
  index: 100,
  symbol: "Fm",
  name: "Fermium",
  atomicNumber: 100,
  position: { row: 7, col: 14 },
  category: "Actinide",
  atomicRadius: "245 pm",
  atomicWeight: "257 amu",
  density: "unknown",
  electroNegativity: "1.3",
  meltingPoint: "1800 K",
  boilingPoint: "unknown",
  standardState: "Solid",
  ionizationEnergy: "627 kJ/mol",
  discoveredBy: "Albert Ghiorso and team",
  discoveredYear: "1952",
  howToPronounce: "FUR-mee-um"
},
{
  index: 101,
  symbol: "Md",
  name: "Mendelevium",
  atomicNumber: 101,
  position: { row: 7, col: 15 },
  category: "Actinide",
  atomicRadius: "246 pm",
  atomicWeight: "258 amu",
  density: "unknown",
  electroNegativity: "1.3",
  meltingPoint: "1100 K",
  boilingPoint: "unknown",
  standardState: "Solid",
  ionizationEnergy: "635 kJ/mol",
  discoveredBy: "Albert Ghiorso, Glenn T. Seaborg, Bernard Harvey, Gregory Choppin, Stanley G. Thompson",
  discoveredYear: "1955",
  howToPronounce: "men-duh-LEE-vee-um"
},
{
  index: 102,
  symbol: "No",
  name: "Nobelium",
  atomicNumber: 102,
  position: { row: 7, col: 16 },
  category: "Actinide",
  atomicRadius: "246 pm",
  atomicWeight: "259 amu",
  density: "unknown",
  electroNegativity: "1.3",
  meltingPoint: "1100 K",
  boilingPoint: "unknown",
  standardState: "Solid",
  ionizationEnergy: "642 kJ/mol",
  discoveredBy: "Joint Institute for Nuclear Research, Dubna",
  discoveredYear: "1966",
  howToPronounce: "no-BEE-lee-um"
},
{
  index: 103,
  symbol: "Lr",
  name: "Lawrencium",
  atomicNumber: 103,
  position: { row: 7, col: 17 },
  category: "Actinide",
  atomicRadius: "246 pm",
  atomicWeight: "266 amu",
  density: "unknown",
  electroNegativity: "1.3",
  meltingPoint: "1900 K",
  boilingPoint: "unknown",
  standardState: "Solid",
  ionizationEnergy: "470 kJ/mol",
  discoveredBy: "Joint Institute for Nuclear Research, Dubna & Lawrence Berkeley Laboratory",
  discoveredYear: "1961",
  howToPronounce: "lor-EN-see-um"
}
]

for (let i = 0; i < actinideElements.length; i++) {
  actinideElements[i] = {
    ...actinideElements[i],
    bg: "#001e33",
    cardBG: "#001321",
    secondCardBG: "#001e33",
    textColor: "#66bfff",
  };
}

console.log(actinideElements);
